<?php
error_reporting( -1 );
ini_set( 'display_errors', 1 );
# Production configuration for SkyWiki - meta.skywiki.org
# This file was automatically generated by the MediaWiki 1.42.3
# installer. If you make manual changes, please keep track in case you
# need to recreate them later.
#
# See includes/MainConfigSchema.php for all configurable settings
# and their default values, but don't forget to make changes in _this_
# file, not there.
#
# Further documentation for configuration settings may be found at:
# https://www.mediawiki.org/wiki/Manual:Configuration_settings

# Protect against web entry
if ( !defined( 'MEDIAWIKI' ) ) {
	exit;
}




## Uncomment this to disable output compression
# $wgDisableOutputCompression = true;

$wgMetaNamespace = 'Test_Wiki';

## The URL base path to the directory containing the wiki;
## defaults for all runtime URL paths are based off of this.
## For more information on customizing the URLs
## (like /w/index.php/Page_title to /wiki/Page_title) please see:
## https://www.mediawiki.org/wiki/Manual:Short_URL
$wgScriptPath = '';

## The protocol and server name to use in fully-qualified URLs

## The URL path to static resources (images, scripts, etc.)
$wgResourceBasePath = $wgScriptPath;

## The URL paths to the logo.  Make sure you change this from the default,
## or else you'll overwrite your logo when you upgrade!

## UPO means: this is also a user preference option

$wgEnableEmail = true;
$wgEnableUserEmail = false; # UPO

$wgEmergencyContact = 'noreply@skywiki.org';
$wgPasswordSender = 'noreply@skywiki.org';

$wgEnotifUserTalk = false; # UPO
$wgEnotifWatchlist = false; # UPO
$wgEmailAuthentication = true;

## Database settings
$wgDBtype = 'mysql';
$wgDBserver = 'localhost';
$wgDBuser = ''; // redacted for security reasons
$wgDBpassword = ''; // redacted for security reasons

# MySQL specific settings
$wgDBprefix = "";
$wgDBssl = false;

# MySQL table options to use during installation or update
$wgDBTableOptions = "ENGINE=InnoDB, DEFAULT CHARSET=binary";

# Shared database table
# This has no effect unless $wgSharedDB is also set.
$wgSharedTables[] = "actor";

## Shared memory settings
$wgMainCacheType = CACHE_ACCEL;
$wgMemCachedServers = [];

## To enable image uploads, make sure the 'images' directory
## is writable, then set this to true:
$wgEnableUploads = true;
$wgUseImageMagick = true;
$wgImageMagickConvertCommand = '/usr/bin/convert';

# InstantCommons allows wiki to use images from https://commons.wikimedia.org
$wgUseInstantCommons = false;

# Periodically send a pingback to https://www.mediawiki.org/ with basic data
# about this MediaWiki instance. The Wikimedia Foundation shares this data
# with MediaWiki developers to help guide future development efforts.
$wgPingback = true;

# Site language code, should be one of the list in ./includes/languages/data/Names.php

# Time zone

## Set $wgCacheDirectory to a writable directory on the web server
## to make your wiki go slightly faster. The directory should not
## be publicly accessible from the web.
#$wgCacheDirectory = "$IP/cache";

$wgSecretKey = ''; // redacted for security reasons

# Changing this will log out all existing sessions.
$wgAuthenticationTokenVersion = '1';

# Site upgrade key. Must be set to a string (default provided) to turn on the
# web installer while LocalSettings.php is in place
$wgUpgradeKey = ''; // redacted for security reasons

## For attaching licensing metadata to pages, and displaying an
## appropriate copyright notice / icon. GNU Free Documentation
## License and Creative Commons licenses are supported so far.
$wgRightsPage = ""; # Set to the title of a wiki page that describes your license/copyright
$wgRightsUrl = '';
$wgRightsText = '';
$wgRightsIcon = "";

# Path to the GNU diff3 utility. Used for conflict resolution.
$wgDiff3 = '/usr/bin/diff3';

## Default skin: you can change the default skin. Use the internal symbolic
## names, e.g. 'vector' or 'monobook':
$wgDefaultSkin = 'vector';

$wgConf->suffixes = [ 'wiki' ];

$wmgUploadHostname = "$wgDBname.skywiki.org";

$wgManageWiki = ['cdb' => false, 'core' => true, 'extensions' => true, 'namespaces' => true, 'permissions' => true, 'settings' => true];

wfLoadExtension( 'CreateWiki' );
wfLoadExtension( 'ManageWiki' );
require_once "$IP/MirahezeFunctions.php";
$wi = new MirahezeFunctions();
$wgConf->settings += [
	// AbuseFilter
	'wgAbuseFilterCentralDB' => [
		'default' => 'metawiki',
		# 'mirabeta' => 'metawikibeta',
	],
	'wgAbuseFilterIsCentral' => [
		'default' => false,
		'metawiki' => true,
		# 'metawikibeta' => true,
	],

	// CentralAuth
	'wgCentralAuthAutoCreateWikis' => [
		'default' => [
			'loginwiki',
			'metawiki',
		],
		'beta' => [
			'loginwikibeta',
			'metawikibeta',
		],
	],
	'wgCentralAuthAutoMigrate' => [
		'default' => false,
	],
	'wgCentralAuthAutoMigrateNonGlobalAccounts' => [
		'default' => false,
	],
	'wgCentralAuthCookies' => [
		'default' => true,
	],
	'wgCentralAuthCookiePrefix' => [
		'default' => 'centralauth_',
		'beta' => 'betacentralauth_',
	],
	'wgCentralAuthDatabase' => [
		'default' => 'centralauth',
		'beta' => 'testglobal',
	],
	'wgCentralAuthEnableGlobalRenameRequest' => [
		'default' => true,
	],
	'wgCentralAuthGlobalBlockInterwikiPrefix' => [
		'default' => 'meta',
	],
	'wgCentralAuthLoginWiki' => [
		'default' => 'loginwiki',
		'beta' => 'loginwikibeta',
	],
	'wgCentralAuthOldNameAntiSpoofWiki' => [
		'default' => 'metawiki',
		'beta' => 'metawikibeta',
	],
	'wgCentralAuthPreventUnattached' => [
		'default' => true,
	],
	'wmgCentralAuthAutoLoginWikis' => [
		'default' => [
			'.skywiki.org' => 'metawiki'
		],
	],


	// CreateWiki
	'wgCreateWikiDatabase' => [
		'default' => 'wikidb',
	],
	'wgCreateWikiUseJobQueue' => [
		'default' => false,
	],
	'wgCreateWikiCategories' => [
		'default' => [
			'Art & Architecture' => 'artarc',
			'Automotive' => 'automotive',
			'Business & Finance' => 'businessfinance',
			'Community' => 'community',
			'Education' => 'education',
			'Electronics' => 'electronics',
			'Entertainment' => 'entertainment',
			'Fandom' => 'fandom',
			'Fantasy' => 'fantasy',
			'Gaming' => 'gaming',
			'Geography' => 'geography',
			'History' => 'history',
			'Humour/Satire' => 'humour',
			'Language/Linguistics' => 'langling',
			'Leisure' => 'leisure',
			'Literature/Writing' => 'literature',
			'Media/Journalism' => 'media',
			'Medicine/Medical' => 'medical',
			'Military/War' => 'military',
			'Music' => 'music',
			'Podcast' => 'podcast',
			'Politics' => 'politics',
			'Private' => 'private',
			'Religion' => 'religion',
			'Science' => 'science',
			'Software/Computing' => 'software',
			'Song Contest' => 'songcontest',
			'Sports' => 'sport',
			'Uncategorised' => 'uncategorised',
		],
	],
	'wgCreateWikiUseCategories' => [
		'default' => true,
	],
	'wgCreateWikiSubdomain' => [
		'default' => 'skywiki.org',
	],
	'wgCreateWikiUseClosedWikis' => [
		'default' => true,
	],
	'wgCreateWikiUseCustomDomains' => [
		'default' => true,
	],
	'wgCreateWikiUseEchoNotifications' => [
		'default' => true,
	],
	'wgCreateWikiUseExperimental' => [
		'default' => true,
	],
	'wgCreateWikiUseInactiveWikis' => [
		'default' => true,
	],
	'wgCreateWikiUsePrivateWikis' => [
		'default' => true,
	],
	'wgCreateWikiCacheDirectory' => [
		'default' => 'cw_cache',
	],
	'wgCreateWikiDatabaseSuffix' => [
		'default' => 'wiki',
	],
	'wgCreateWikiDisableRESTAPI' => [
		'default' => true,
		'metawiki' => false,
	],
	'wgCreateWikiGlobalWiki' => [
		'default' => 'metawiki',
	],
	'wgCreateWikiEmailNotifications' => [
		'default' => true,
	],
	'wgCreateWikiInactiveExemptReasonOptions' => [
		'default' => [
			'Wiki completed and made to be read' => 'comp',
			'Wiki made for time-based gathering' => 'tbg',
			'Wiki made to be read' => 'mtr',
			'Temporary exemption for exceptional hardship, see DPE' => 'temphardship',
			'Other, see DPE' => 'other',
		],
	],
	'wgCreateWikiCannedResponses' => [
		'default' => [
			'Approval reasons' => [
				'Approved' => 'Please make sure that you follow the Content Policy at all times and not deviate from the mentioned scope or your wiki may be closed. Thank you for choosing SkyWiki.',
			],
		],
	],
	'wgCreateWikiDisallowedSubdomains' => [
		'default' => [
			'www',
			'ftp',
			'mail',
			'webmail',
			'admin',
			'administrator',
			'hostmaster',
			'webmaster',
			'abuse',
			'contact',
			'info',
			'privacy',
			'legal',
			'help',
			'support',
			'blog',
			'wiki',
			'wiki2',
			'forums',
			'forum',
			'phorge',
			'phabricator',
			'phab',
			'issues',
			'bugzilla',
			'issue-tracker',
		]
	],
	'wgCreateWikiStateDays' => [
		'default' => [
			'inactive' => 90,
			'closed' => 30,
			'removed' => 999,
			'deleted' => 999,
		]
	],
	'wgCreateWikiEnableManageInactiveWikis' => [
		'default' => true,
	],
	'wgCreateWikiSQLFiles' => [
		'default' => [
			"$IP/maintenance/tables-generated.sql",
			"$IP/extensions/AbuseFilter/db_patches/mysql/tables-generated.sql",
			"$IP/extensions/AntiSpoof/sql/mysql/tables-generated.sql",
			"$IP/extensions/BetaFeatures/sql/tables-generated.sql",
			"$IP/extensions/CheckUser/schema/mysql/tables-generated.sql",
			"$IP/extensions/DataDump/sql/data_dump.sql",
			"$IP/extensions/Echo/sql/mysql/tables-generated.sql",
			"$IP/extensions/GlobalBlocking/sql/mysql/tables-generated-global_block_whitelist.sql",
			"$IP/extensions/OATHAuth/sql/mysql/tables-generated.sql",
			"$IP/extensions/OAuth/schema/mysql/tables-generated.sql",
			"$IP/extensions/GlobalPreferences/sql/mysql/tables-generated.sql",
			//"$IP/extensions/RottenLinks/sql/rottenlinks.sql",
			//"$IP/extensions/UrlShortener/schemas/tables-generated.sql",
		],
	],

	// CreateWiki Defined Special Variables
	'cwClosed' => [
		'default' => false,
	],
	'cwDeleted' => [
		'default' => false,
	],
	'cwExperimental' => [
		'default' => false,
	],
	'cwInactive' => [
		'default' => false,
	],
	'cwPrivate' => [
		'default' => false,
	],

	// for Cloudflare
	'wgUsePrivateIPs' => [
		'default' => true,
	],
	'wgCdnServersNoPurge' => [
		'default' => [
			// IPv4 addresses
			"103.21.244.0/22",
			"103.22.200.0/22",
			"103.31.4.0/22",
			"104.16.0.0/13",
			"104.24.0.0/14",
			"108.162.192.0/18",
			"131.0.72.0/22",
			"141.101.64.0/18",
			"162.158.0.0/15",
			"172.64.0.0/13",
			"173.245.48.0/20",
			"188.114.96.0/20",
			"190.93.240.0/20",
			"197.234.240.0/22",
			"198.41.128.0/17",

			// IPv6 addresses
			"2400:cb00::/32",
			"2606:4700::/32",
			"2803:f800::/32",
			"2405:b500::/32",
			"2405:8100::/32",
			"2a06:98c0::/29",
		],
	],

	'wmgSharedUploadDBname' => [
		'default' => false,
	],
	'wgFileExtensions' => [
		'default' => [
			'djvu',
			'gif',
			'ico',
			'jpg',
			'jpeg',
			'ogg',
			'pdf',
			'png',
			'svg',
			'webp',
		],
	],
	'wgArticlePath' => [
		'default' => '/wiki/$1',
	],
	'wgScriptPath' => [
		'default' => '',
	],
	'wgUsePathInfo' => [
		'default' => true,
	],
	'wgResourceBasePath' => [
		'default' => '',
	],
	'wgManageWikiPermissionsAdditionalAddGroups' => [
		'default' => [],
	],
	'wgManageWikiPermissionsAdditionalRights' => [
		'default' => [
			'*' => [
				'autocreateaccount' => true,
				'read' => true,
				'oathauth-enable' => true,
				'viewmyprivateinfo' => true,
				'editmyoptions' => true,
				'editmyprivateinfo' => true,
				'editmywatchlist' => true,
				'writeapi' => true,
			],
			'checkuser' => [
				'checkuser' => true,
				'checkuser-log' => true,
				'abusefilter-privatedetails' => true,
				'abusefilter-privatedetails-log' => true,
			],
			'suppress' => [
				'abusefilter-hidden-log' => true,
				'abusefilter-hide-log' => true,
				'browsearchive' => true,
				'deletedhistory' => true,
				'deletedtext' => true,
				'deletelogentry' => true,
				'deleterevision' => true,
				'hideuser' => true,
				'suppressionlog' => true,
				'suppressrevision' => true,
				'viewsuppressed' => true,
			],
			'steward' => [
				'userrights' => true,
			],
			'user' => [
				'mwoauthmanagemygrants' => true,
				'user' => true,
			],
		],
		'+metawiki' => [
			'steward' => [
				'abusefilter-modify-global' => true,
				'centralauth-lock' => true,
				'centralauth-suppress' => true,
				'centralauth-rename' => true,
				'centralauth-unmerge' => true,
				'createwiki' => true,
				'createwiki-deleterequest' => true,
				'globalblock' => true,
				'handle-import-request-interwiki' => true,
				'handle-import-requests' => true,
				'managewiki-core' => true,
				'managewiki-extensions' => true,
				'managewiki-namespaces' => true,
				'managewiki-permissions' => true,
				'managewiki-settings' => true,
				'managewiki-restricted' => true,
				'noratelimit' => true,
				'oathauth-verify-user' => true,
				'userrights' => true,
				'userrights-interwiki' => true,
				'globalgroupmembership' => true,
				'globalgrouppermissions' => true,
				'view-private-import-requests' => true,
			],
			'user' => [
				'createnewwiki' => true,
			]
		]
	],
	'wgManageWikiPermissionsAdditionalRemoveGroups' => [
		'default' => [],
	],
	'wgManageWikiPermissionsDisallowedRights' => [
		'default' => [
			'any' => [
				'abusefilter-hide-log',
				'abusefilter-hidden-log',
				'abusefilter-modify-global',
				'abusefilter-private',
				'abusefilter-private-log',
				'abusefilter-privatedetails',
				'abusefilter-privatedetails-log',
				'aft-oversighter',
				'autocreateaccount',
				'bigdelete',
				'centralauth-createlocal',
				'centralauth-lock',
				'centralauth-suppress',
				'centralauth-rename',
				'centralauth-unmerge',
				'checkuser',
				'checkuser-log',
				'createwiki',
				'createwiki-deleterequest',
				'createwiki-suppressionlog',
				'createwiki-suppressrequest',
				'editincidents',
				'editothersprofiles-private',
				'flow-suppress',
				'generate-random-hash',
				'globalblock',
				'globalblock-exempt',
				'globalgroupmembership',
				'globalgrouppermissions',
				'handle-import-request-interwiki',
				'handle-import-requests',
				'handle-pii',
				'hideuser',
				'investigate',
				'ipinfo',
				'ipinfo-view-basic',
				'ipinfo-view-full',
				'ipinfo-view-log',
				'managewiki-restricted',
				'managewiki-editdefault',
				'moderation-checkuser',
				'mwoauthmanageconsumer',
				'mwoauthmanagemygrants',
				'mwoauthsuppress',
				'mwoauthviewprivate',
				'mwoauthviewsuppressed',
				'oathauth-api-all',
				'oathauth-enable',
				'oathauth-disable-for-user',
				'oathauth-verify-user',
				'oathauth-view-log',
				'renameuser',
				'request-import',
				'requestwiki',
				'siteadmin',
				'securepoll-view-voter-pii',
				'smw-admin',
				'smw-patternedit',
				'smw-viewjobqueuewatchlist',
				'stopforumspam',
				'suppressionlog',
				'suppressrevision',
				'themedesigner',
				'titleblacklistlog',
				'updatepoints',
				'userrights',
				'userrights-interwiki',
				'view-private-import-requests',
				'viewglobalprivatefiles',
				'viewpmlog',
				'viewsuppressed',
				'writeapi',
			],
			'user' => [
				'autoconfirmed',
				'noratelimit',
				'skipcaptcha',
				'managewiki-core',
				'managewiki-extensions',
				'managewiki-namespaces',
				'managewiki-permissions',
				'managewiki-settings',
				'globalblock-whitelist',
				'ipblock-exempt',
				'interwiki',
			],
			'*' => [
				'read',
				'skipcaptcha',
				'torunblocked',
				'centralauth-merge',
				'generate-dump',
				'editsitecss',
				'editsitejson',
				'editsitejs',
				'editusercss',
				'edituserjson',
				'edituserjs',
				'editmyoptions',
				'editmyprivateinfo',
				'editmywatchlist',
				'globalblock-whitelist',
				'interwiki',
				'ipblock-exempt',
				'viewmyprivateinfo',
				'viewmywatchlist',
				'managewiki-core',
				'managewiki-extensions',
				'managewiki-namespaces',
				'managewiki-permissions',
				'managewiki-settings',
				'noratelimit',
				'autoconfirmed',
			],
		],
	],
	'wgManageWikiPermissionsDisallowedGroups' => [
		'default' => [
			'checkuser',
			'smwadministrator',
			'oversight',
			'steward',
			'staff',
			'suppress',
			'techteam',
			'trustandsafety',
		],
	],
	'wgVirtualDomainsMapping' => [
		'default' => [
			'virtual-createwiki' => [ 'db' => 'wikidb' ],
			'virtual-createwiki-central' => [ 'db' => 'metawiki' ],
		]
	],
	'wgManageWikiPermissionsDefaultPrivateGroup' => [
		'default' => 'member',
	],

	'wgWhitelistRead' => [
		'default' => [
			'Special:UserLogin',
			'Special:UserLogout',
			'Special:CreateAccount',
			'Main Page',
		],
	],
	'wgWhitelistReadRegexp' => [
		'default' => [
			'/^(Special):CentralAutoLogin.*/',
			'/^(Special):CentralLogin.*/',
		],
	],

	'wgManageWikiExtensionsDefault' => [
		'default' => [
			'categorytree',
			'cite',
			'citethispage',
			'codeeditor',
			'codemirror',
			'darkmode',
			'globaluserpage',
			'minervaneue',
			'mobilefrontend',
			'syntaxhighlight_geshi',
			'textextracts',
			'urlshortener',
			'wikiseo',
		],
	],

	'wgUseImageMagick' => [
		'default' => true,
	],
	'wgImageMagickConvertCommand' => [
		'default' => '/usr/bin/convert',
	],

	'wgSharedTables' => [
		'default' => [],
	],

	'wgEnableUploads' => [
		'default' => true,
	],




	// OATHAuth
	'wgOATHExclusiveRights' => [
		'default' => [
			'abusefilter-privatedetails',
			'abusefilter-privatedetails-log',
			'centralauth-lock',
			'centralauth-rename',
			'centralauth-suppress',
			'checkuser',
			'checkuser-log',
			'globalblock',
			'globalgrouppermissions',
			'globalgroupmembership',
			'securepoll-view-voter-pii',
			'suppressionlog',
			'suppressrevision',
			'userrights',
			'userrights-interwiki',
		],
		'+metawiki' => [
			'edituserjs',
			'editsitejs',
		],
	],
	'wgOATHRequiredForGroups' => [
		'default' => [
			'checkuser',
			'suppress',
			'steward',
		],
		'+metawiki' => [
			'electionadmin',
			'global-admin',
			'interface-admin',
			'techteam',
			'trustandsafety'
		],
		// metawikibeta should mirror metawiki
		'+metawikibeta' => [
			'global-admin',
			'interface-admin',
			'techteam',
			'trustandsafety'
		],
	],
	// OAuth
	'wgMWOAuthCentralWiki' => [
		'default' => 'metawiki',
		'ldapwikiwiki' => false,
		'srewiki' => false,
		'beta' => 'metawikibeta',
	],
	'wgOAuth2GrantExpirationInterval' => [
		'default' => 'PT4H',
	],
	'wgOAuth2RefreshTokenTTL' => [
		'default' => 'P365D',
	],
	'wgMWOAuthSharedUserSource' => [
		'default' => 'CentralAuth',
	],
	'wgMWOAuthSecureTokenTransfer' => [
		'default' => true,
	],
	'wgOAuth2PublicKey' => [
		'default' => '/var/www/mediawiki/OAuth2.key.pub',
	],
	'wgOAuth2PrivateKey' => [
		'default' => '/var/www/mediawiki/OAuth2.key',
	],


	// Interwiki
	'wgEnableScaryTranscluding' => [
		'default' => true,
	],
	'wgInterwikiCentralDB' => [
		'default' => 'metawiki',
		'beta' => 'metawikibeta',
	],
	'wgExtraInterlanguageLinkPrefixes' => [
		'default' => [
			'simple',
		],
	],
	'wgExtraLanguageNames' => [
		'default' => [
			// Prevent mh from being treated as an interlanguage link (T11615)
			'mh' => '',
		],
	],

	// InterwikiDispatcher
	'wgIWDPrefixes' => [
		'default' => [
			'fandom' => [
				/** Fandom */
				'interwiki' => 'fandom',
				'url' => 'https://$2.fandom.com/wiki/$1',
				'urlInt' => 'https://$2.fandom.com/$3/wiki/$1',
				'baseTransOnly' => true,
			],
			'miraheze' => [
				/** Miraheze */
				'interwiki' => 'mh',
				'url' => 'https://$2.miraheze.org/wiki/$1',
				'dbname' => '$2wiki',
				'baseTransOnly' => true,
			],
			'wikitide' => [
				/** WikiTide */
				'interwiki' => 'wt',
				'url' => 'https://$2.wikitide.org/wiki/$1',
				'baseTransOnly' => true,
			],
			'wikiforge' => [
				/** WikiForge */
				'interwiki' => 'wf',
				'url' => 'https://$2.wikiforge.net/wiki/$1',
				'baseTransOnly' => true,
			],
			'skywiki' => [
				/** SkyWiki */
				'interwiki' => 'skywiki',
				'url' => 'https://$2.skywiki.org/wiki/$1',
				'baseTransOnly' => true,
			],
			'wikioasis' => [
				/** WikiOasis */
				'interwiki' => 'wikioasis',
				'url' => 'https://$2.wikioasis.org/wiki/$1',
				'baseTransOnly' => true,
			],
		],
	],

	// InterwikiSorting
	'wgInterwikiSortingSort' => [
		'ext-InterwikiSorting' => 'code',
	],

	// ImportDump
	'wgImportDumpEnableAutomatedJob' => [
		'default' => true,
	],
	'wgImportDumpInterwikiMap' => [
		'default' => [
			'fandom.com' => 'wikia',
			'miraheze.org' => 'mh',
			'skywiki.org' => 'skywiki',
			'wikioasis.org' => 'wikioasis',
		],
	],
	'wgImportDumpScriptCommand' => [
		'default' => 'php {IP}/maintenance/importDump.php --wiki={wiki} --username-prefix="{username-prefix}" {file-path}',
	],
	'wgImportDumpUsersNotifiedOnAllRequests' => [
		'default' => [
		],
	],
	'wgImportDumpUsersNotifiedOnFailedImports' => [
		'default' => [
		],
	],

	// Imports
	'wgImportSources' => [
		'default' => [
			'meta',
			'mh',
			'mhdev',
			'loginwiki',
			'mw',
			'wikipedia',
			'metawikimedia',
		],
	],

	'wgExportMaxHistory' => [
		'default' => 1000
	],

	'wgIgnoreImageErrors' => [
		'default' => true
	],

	'wgDefaultSkin' => [
		'default' => 'vector-2022',
	],
	'wgFallbackSkin' => [
		'default' => 'vector-2022',
	],
	'wgFavicon' => [
		'default' => '/favicon.ico',
	],
	'wgIcon' => [
		'default' => false,
	],
	'wgWordmark' => [
		'default' => false,
	],
	'wgWordmarkHeight' => [
		'default' => 18,
	],
	'wgWordmarkWidth' => [
		'default' => 116,
	],
        '+wgVirtualDomainsMapping' => [
                'default' => [
                        'virtual-botpasswords' => [
                                'db' => 'centralauth',
                        ],
                        'virtual-centralauth' => [
                                'db' => 'centralauth',
                        ],
                        'virtual-globalblocking' => [
                                'db' => 'centralauth',
                        ],
                        'virtual-oathauth' => [
                                'db' => 'centralauth',
                        ],
                        'virtual-importdump' => [
                                'db' => 'metawiki',
                        ],
                        'virtual-createwiki' => [
                                'db' => 'wikidb',
                        ],
                        'virtual-createwiki-central' => [
                                'db' => 'metawiki',
                        ],
                        'virtual-requestssl' => [
                                'db' => 'centralauth',
                        ],
                ],
        ],
];
require_once "$IP/ManageWikiExtensions.php";
$globals = MirahezeFunctions::getConfigGlobals();

// phpcs:ignore MediaWiki.Usage.ForbiddenFunctions.extract
extract($globals);
$wi->loadExtensions();
require_once __DIR__ . '/ManageWikiNamespaces.php';
require_once __DIR__ . '/ManageWikiSettings.php';

require_once "$IP/GlobalSettings.php";
require_once "$IP/GlobalExtensions.php";

$wgUploadDirectory = "$IP/images/$wgDBname";
$wgUploadPath = "$wgScriptPath/images/$wgDBname";

if ( $cwPrivate ) {
	$wgUploadDirectory = "/var/www/images/$wgDBname";
	$wgUploadPath = '/img_auth.php';
}
if ( $wi->missing ) {
	require_once '/var/www/mediawiki/ErrorPages/MissingWiki.php';
	http_response_code(404);
#	exit();
}

if ( $cwDeleted ) {
	if ( MW_ENTRY_POINT === 'cli' ) {
		wfHandleDeletedWiki();
	} else {
		define( 'MW_FINAL_SETUP_CALLBACK', 'wfHandleDeletedWiki' );
	}
}

function wfHandleDeletedWiki() {
	require_once '/var/www/mediawiki/ErrorPages/DeletedWiki.php';
	exit();
}

# End of automatically generated settings.
# Add more configuration options below.

$wgSMTP = [
    'host'      => 'smtp.ionos.com', // could also be an IP address. Where the SMTP server is located. If using SSL or TLS, add the prefix "ssl://" or "tls://".
    'IDHost'    => 'skywiki.org',      // Generally this will be the domain name of your website (aka mywiki.org)
    'localhost' => 'skywiki.org',      // Same as IDHost above; required by some mail servers
    'port'      => 587,                // Port to use when connecting to the SMTP server
    'auth'      => true,               // Should we use SMTP authentication (true or false)
    'username'  => 'noreply@skywiki.org',     // Username to use for SMTP authentication (if being used)
    'password'  => ''       // Password to use for SMTP authentication (if being used); redacted for security reasons
];

$wgSessionCacheType = CACHE_DB;

$wgMaxUploadSize = 1024 * 1024 * 25;
$wmgUploadHostname = "meta.skywiki.org";
$wgForceHTTPS = true;
#require_once "$IP/config/LocalSettings.php";
$wgShowExceptionDetails = true;
#$wgDebugLogFile = "/var/log/mediawiki/debug-{$wgDBname}.log";
$wgDebugLogGroups['ImportDump'] = "/var/log/mediawiki/id.log";
$wgDebugLogGroups['SkywikiMagic'] = "/var/log/mediawiki/wom.log";
